<article id="legal_container" class="container">
	<div class="row">
		<div id="legal_text">
			<h1>Third party Sources</h1>
			<ul>
				<li><a href="pixabay.com">pixabay.com</a></li>
				<li><a href="fontello.com">fontello.com</a></li>
				<li><a href="getbootstrap.com">getbootstrap.com</a></li>
				<li><a href="http://www.brainyquote.com/link/index.html">http://www.brainyquote.com/link/index.html</a></li>
			</ul>
		</div>
	</div>
</article>