<?php
	$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('cv/add', array('type' => 'vita')));
$form->prepare();

echo $this->form()->openTag($form);
// echo $this->formRow($form->get('title'));
// echo $this->formSubmit($form->get('submit'));
foreach ($form as $element) {
	echo $this->formRow($element);
}
echo $this->form()->closeTag();