<div class="row-fluid" class="holder">
    <section id="news_box">
        <div class="overlay">
        	<div id="news_container" class="container">
                <div class="row">
        			<article id="news_article">
        				<div class="inner">
        					<h2 class="news-heading">
                                News
                                <a href="#"><figure class="pull-right"></figure></a>
                                <a href="#"><figure class="pull-right"></figure></a>
                                <a href="#"><figure class="pull-right"></figure></a>
                                <a href="#"><figure class="pull-right"></figure></a>
                                <a href="#"><figure class="pull-right active"></figure></a>
                            </h2>
        					<div class="actual-news">
                                <article class="news-entry">
                                    <div class="creation-date">
                                        11-08-2014
                                    </div>
                                    <div class="category-item">
                                        <i class="icon icon-laptop"></i>
                                    </div>
                                    <h3>Lorem ipsum</h3>
                                    Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.
                                </article>
        					</div>
        				</div>
        			</article>
        			<article id="news_cat_article">
        				<div class="inner">
        					<h2 class="news-heading"><?php echo $this->translate('News navigation'); ?></h2>
                            <div class="actual-news">
                                <div class="list-group">
                                    <a href="#" class="list-group-item active">
                                        <?php echo $this->translate('Work'); ?>
                                        <span class="badge">15</span>
                                    </a>
                                    <a href="#" class="list-group-item">
                                        <?php echo $this->translate('About me'); ?>
                                        <span class="badge">2</span>
                                    </a>
                                    <a href="#" class="list-group-item">
                                        <?php echo $this->translate('Curriculum Vitae'); ?>
                                        <span class="badge">1</span>
                                    </a>
                                    <a href="#" class="list-group-item">
                                        <?php echo $this->translate('Blog'); ?>
                                        <span class="badge">6</span>
                                    </a>
                                </div>
                            </div>
        				</div>
        			</article>
                </div>
            </div>
            <i class="background-icon icon-newspaper"></i>
        </div>
    </section>
</div>
<div class="container">
    <div class="row">
        
        <div id="welcome_text">
            <h1>Hi there welcome to my Portfolio and Blog</h1>
            <p>
            I’m Stanislaw Gutsch — a web developer who believes in simple, modular and reusable code that speaks clearly and provides consistent user experiences across devices.
            <br/><br/>
            At the moment I'am a developer for a web agency based in Koblenz Germany. I like coffee the interwebs, astronomy, programming and dogs.
            <br/><br/>
            In here I'll mostly write about programming, work and my daily life. 
            </p>
        </div>
    </div>
</div>
<div class="row-fluid" class="holder">
    <section id="welcome_image">
        <aside id="qoute_container">
            <script type="text/javascript" src="http://www.brainyquote.com/link/quotebr.js"></script>
            <small>
                <i>
                    <a href="http://www.brainyquote.com/quotes_of_the_day.html" target="_blank">more Quotes</a>
                </i>
            </small>
        </aside>
    </section>
</div>
<div class="row-fluid">
    <section id="social">
        <div class="item">
            <a href="mailto:<?php echo $social['e-mail']; ?>">
                <i class="icon icon-mail"></i>
            </a>
        </div>
        <div class="item">
            <a href="<?php echo $social['stackoverflow']; ?>">
                <i class="icon icon-stackoverflow"></i>
            </a>
        </div>
        <div class="item">
            <a href="<?php echo $social['g-plus']; ?>">
                <i class="icon icon-googleplus-rect"></i>
            </a>
        </div>
    </section>
</div>
<script src="<?php echo $this->basePath(); ?>/js/jquery.firefly.js"></script>
<script src="<?php echo $this->basePath(); ?>/js/initFlies.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/js/application.js"></script>